# Generated by Django 5.1 on 2024-09-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.BigIntegerField()),
                ('name', models.CharField(max_length=60)),
                ('longname', models.CharField(max_length=120)),
                ('teacher', models.CharField(max_length=60)),
                ('room', models.CharField(max_length=60)),
                ('startBlock', models.BigIntegerField()),
                ('endBlock', models.BigIntegerField()),
                ('notes', models.CharField(max_length=400)),
            ],
        ),
    ]
