# Generated by Django 5.1 on 2024-09-05 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icsapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='day',
        ),
        migrations.RemoveField(
            model_name='course',
            name='endBlock',
        ),
        migrations.RemoveField(
            model_name='course',
            name='longname',
        ),
        migrations.RemoveField(
            model_name='course',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='course',
            name='room',
        ),
        migrations.RemoveField(
            model_name='course',
            name='startBlock',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icsapi.course')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('longname', models.CharField(max_length=200)),
                ('dozent', models.CharField(max_length=100)),
                ('raum', models.CharField(max_length=50)),
                ('startBlock', models.IntegerField()),
                ('endBlock', models.IntegerField()),
                ('notes', models.CharField(max_length=500)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icsapi.timetable')),
            ],
        ),
    ]
